// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripPlanner.Models;

namespace TripPlanner.Migrations
{
    [DbContext(typeof(TripPlannerContext))]
    [Migration("20191005054618_identity")]
    partial class identity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TripPlanner.Models.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Note");

                    b.Property<int>("TripId");

                    b.HasKey("DayId");

                    b.HasIndex("TripId");

                    b.ToTable("days");
                });

            modelBuilder.Entity("TripPlanner.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("TripEndDate");

                    b.Property<string>("TripLocation");

                    b.Property<string>("TripName");

                    b.Property<DateTime>("TripStartDate");

                    b.Property<int>("UserProfileId");

                    b.HasKey("TripId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("TripPlanner.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("ApplicationUserId");

                    b.Property<string>("Gender");

                    b.Property<string>("Image");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("UserProfileId");

                    b.ToTable("userprofiles");
                });

            modelBuilder.Entity("TripPlanner.Models.Day", b =>
                {
                    b.HasOne("TripPlanner.Models.Trip")
                        .WithMany("Days")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TripPlanner.Models.Trip", b =>
                {
                    b.HasOne("TripPlanner.Models.UserProfile")
                        .WithMany("Trips")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
